### ISSUE TITLE
axes are misaligned for N > 1 distributions

### ISSUE THREAD

**Issue by ElKatz** [jcbyts/pdstools#4]
When plotting N distributions the ordinate of the histogram is variable.
Perhaps a 'count' variable akin to 'bcenters' should be passed in so that the already at the first plot of N the ordinate is scaled accordingly?

![screen shot 2015-10-11 at 5 38 40 pm](https://cloud.githubusercontent.com/assets/5068044/10419576/5420319e-7041-11e5-949e-5e5d4620987e.png)

**Comment by jcbyts** [comment]
Good catch! We should put the RNGE variable in projectedHistogram into effect. Right now it scales the plot, but it could scale the normalization instead.

**Comment by jcbyts** [comment]
new option `'MaxCount'` in `plotUnityHistogram` will scale the variable `Normzer` in `projectedHistogram`

**Comment by jcbyts** [comment]
It's not a perfect solution, but it gets the job done. Using `plotUnityHistogram`, you can pass in options to scale the histogram: 
`'Yscale'`         scales the histogram in the plot (once it's already been normalized)
`MaxCount`    changes the normalization

We probably should have just 1 variable for this, but I'll set that as a long term goal. This will get you running for the poster deadline
