### ISSUE TITLE
abscissa misaligned 

### ISSUE THREAD

**Issue by ElKatz** [jcbyts/pdstools#5]
You move the x axis just a bit (Movshon-style..) but a line (in 'Color') remains, and the data is a bit misaligned to it.

![screen shot 2015-10-11 at 5 55 23 pm](https://cloud.githubusercontent.com/assets/5068044/10419570/4447ca52-7041-11e5-8b40-1471e128f91a.png)

**Comment by jcbyts** [comment]
I believe the data aren't misaligned. That's just a bin with count=0.

**Comment by jcbyts** [comment]
Yea, data aren't misaligned. The ticks just go where the bin centers are... I suppose we could make an option for bin edges.

![screen shot 2015-10-11 at 6 08 59 pm](https://cloud.githubusercontent.com/assets/1760049/10419645/3e226540-7043-11e5-9db7-2eb3374e214b.png)

**Comment by ElKatz** [comment]
perfect. great QAing. 
So ticks are bin CENTERS. 
As long as we knoe that, I think this isuue can be marked resolved
